environment:
  matrix:
    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python
    - TOXENV: "py27"
    - TOXENV: "py35"
    - TOXENV: "py36"
    - TOXENV: "pypy"
    - TOXENV: "docs"

install:
  - if "%TOXENV%"=="pypy" choco install python.pypy
  - if "%TOXENV%"=="pypy" set PATH=C:\tools\pypy\pypy;%PATH% # so tox can find pypy

  - pip install tox

build: off

test_script:
  - tox -e %TOXENV%
